version: "3.9"
services:
  app:
    image: sibbl/matrix-bot-media-fetcher
    environment:
      HOMESERVER_URL: https://matrix.org
      ACCESS_TOKEN: ""
      OUTPUT_PATH: /home/data
      # MSG_TYPES: m.image,m.video,m.audio,m.file
    volumes:
      - ./data:/home/data